# Generated by Django 3.2.13 on 2022-11-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20221112_0026'),
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alarm_subscription', to='subscriptions.subscription', verbose_name='구독정보'),
        ),
    ]
