# Generated by Django 3.2.13 on 2022-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0004_alter_alarm_d_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmhistory',
            name='traceback',
            field=models.TextField(blank=True, default='', null=True, verbose_name='발송 실패 원인'),
        ),
    ]
