# Generated by Django 3.2.13 on 2022-11-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20221122_0014'),
        ('alarms', '0005_alter_alarmhistory_traceback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_subscription', to='subscriptions.subscription', verbose_name='구독정보'),
        ),
        migrations.AlterField(
            model_name='alarmhistory',
            name='alarm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alarms.alarm', verbose_name='알림'),
        ),
    ]
