# Generated by Django 3.2.13 on 2022-11-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0006_auto_20221122_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='delete_on',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
    ]
