# Generated by Django 3.2.13 on 2022-11-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0007_alarm_delete_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='delete_on',
        ),
        migrations.AddField(
            model_name='alarm',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성 여부'),
        ),
    ]
