# Generated by Django 3.2.13 on 2022-11-23 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0008_auto_20221122_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='is_active',
        ),
    ]
