# Generated by Django 3.2.13 on 2022-11-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0009_remove_alarm_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmhistory',
            name='is_success',
        ),
        migrations.RemoveField(
            model_name='alarmhistory',
            name='traceback',
        ),
    ]
