# Generated by Django 3.2.13 on 2022-11-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20221122_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='delete_on',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='delete_on',
        ),
    ]
