# Generated by Django 3.2.13 on 2022-11-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20221122_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='delete_on',
            field=models.BooleanField(default=True, verbose_name='삭제 여부'),
        ),
    ]
