# Generated by Django 3.2.13 on 2022-11-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_delete_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delete_on',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
    ]
