# Generated by Django 3.2.13 on 2022-12-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_delete_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '-- 선택 --'), (1, 'OTT'), (2, '음악'), (3, '도서'), (4, '유통'), (5, '소프트웨어'), (6, '정기배송'), (7, '렌탈')], unique=True, verbose_name='카테고리 종류'),
        ),
        migrations.AlterField(
            model_name='type',
            name='method_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '-- 선택 --'), (1, '신용카드'), (2, '체크카드'), (3, '계좌이체'), (4, '간편결제'), (5, '휴대폰결제')], unique=True, verbose_name='결제유형'),
        ),
    ]
